// LOGIN

export const LOGIN = 'LOGIN'
export const LOGIN_CHECK = 'LOGIN_CHECK'

// PROFILE

export const LOAD_DATA = 'LOAD_DATA'
export const CHANGE_OFF_IS_PROFILE = 'CHANGE_OFF_IS_PROFILE'

// MESSAGES

export const CHANGE_LOCAL_MESSAGE = 'CHANGE_LOCAL_MESSAGE'
export const ADD_MESSAGE = 'ADD_MESSAGE'